In [141]:
import pandas as pd

# Dados das marcas, valores e variações (ajuste os valores e variações conforme necessário)
data = {
    "Marca": [
        "Itaú", "Banco do Brasil", "Bradesco", "Petrobras", "Vale", 
        "Caixa", "Localiza", "Brahma", "Natura", "Skol", 
        "Sadia", "Vivo", "Rede D’or São Luiz", "Nubank", "Marfrig", 
        "Latam Airlines", "Assai Atacadista", "Raízen", "Magazine Luiza", "Antarctica", 
        "Suzano", "Ipiranga", "Embraer", "Braskem", "Atacadão", 
        "Unidas", "Sabesp", "Klabin", "Movida", "PagSeguro Digital", 
        "Renner", "Camil", "Votorantim", "Globo", "Vibra", 
        "XP Inc.", "BNDES", "Gerdau", "Seguradora Porto", "Itambé", 
        "SmartFit", "Minerva", "Stone", "Perdigão", "Neoenergia", 
        "Hapvida", "B3", "Sul América", "Ypióca", "Banco Pan"
    ],
    "Valor": [
        8330000000, 5450000000, 5010000000, 3400000000, 3000000000, 
        2860000000, 2300000000, 1960000000, 1950000000, 1900000000, 
        1800000000, 1700000000, 1370000000, 1350000000, 1350000000, 
        1220000000, 1200000000, 1090000000, 994000000, 992000000, 
        920000000, 918000000, 864000000, 827000000, 820000000, 
        766000000, 751000000, 693000000, 682000000, 630000000, 
        615000000, 574000000, 569000000, 558000000, 553000000, 
        544000000, 543000000, 536000000, 500000000, 444000000, 
        432000000, 426000000, 416000000, 390000000, 388000000, 
        377000000, 358000000, 357000000, 354000000, 342000000
    ],
    "Variação (%)": [
        -4, 11, -2, -13, 38,
        -7, 90, 20, -2, 7,
        16, 18, 54, 30, 11,
        10, -13, -24, 0, -4,
        34, 30, 6, 6, -39,
        22, 27, -4, -9, 27,
        -4, 0, 10, 5, -16,
        -3, 13, 26, 16, -21,
        -7, 54, 0, 18, -8,
        -2, 6, 8, 14, 0  # Ajuste conforme necessário
    ]
}

# Verificando se todas as listas têm o mesmo comprimento
print(f"Comprimento das listas: {len(data['Marca'])}, {len(data['Valor'])}, {len(data['Variação (%)'])}")

# Cria o DataFrame
df = pd.DataFrame(data)

# Exibe o DataFrame
print(df)

Comprimento das listas: 50, 50, 50
                 Marca       Valor  Variação (%)
0                 Itaú  8330000000            -4
1      Banco do Brasil  5450000000            11
2             Bradesco  5010000000            -2
3            Petrobras  3400000000           -13
4                 Vale  3000000000            38
5                Caixa  2860000000            -7
6             Localiza  2300000000            90
7               Brahma  1960000000            20
8               Natura  1950000000            -2
9                 Skol  1900000000             7
10               Sadia  1800000000            16
11                Vivo  1700000000            18
12  Rede D’or São Luiz  1370000000            54
13              Nubank  1350000000            30
14             Marfrig  1350000000            11
15      Latam Airlines  1220000000            10
16    Assai Atacadista  1200000000           -13
17              Raízen  1090000000           -24
18      Magazine Luiza   994000000             0
19          Antarctica   992000000            -4
20              Suzano   920000000            34
21            Ipiranga   918000000            30
22             Embraer   864000000             6
23             Braskem   827000000             6
24            Atacadão   820000000           -39
25              Unidas   766000000            22
26              Sabesp   751000000            27
27              Klabin   693000000            -4
28              Movida   682000000            -9
29   PagSeguro Digital   630000000            27
30              Renner   615000000            -4
31               Camil   574000000             0
32          Votorantim   569000000            10
33               Globo   558000000             5
34               Vibra   553000000           -16
35             XP Inc.   544000000            -3
36               BNDES   543000000            13
37              Gerdau   536000000            26
38    Seguradora Porto   500000000            16
39              Itambé   444000000           -21
40            SmartFit   432000000            -7
41             Minerva   426000000            54
42               Stone   416000000             0
43            Perdigão   390000000            18
44          Neoenergia   388000000            -8
45             Hapvida   377000000            -2
46                  B3   358000000             6
47         Sul América   357000000             8
48              Ypióca   354000000            14
49           Banco Pan   342000000             0

In [143]:
# Supõe que o DataFrame 'df' já foi criado e contém a coluna 'Valor'
cotacao_dolar = 5

# Converte os valores de dólares para reais e depois para bilhões de reais
df["Valor em bilhões de reais"] = df["Valor"] * cotacao_dolar

df["Variação (%)"] = df["Variação (%)"].astype(str) + '%'

# Adiciona uma coluna de contador
df["Posicao"] = [f"{i+1}ª" for i in range(len(df))]

In [145]:
df = df.drop(columns=["Valor"])

In [147]:
df

                 Marca Variação (%)  Valor em bilhões de reais Posicao
0                 Itaú          -4%                41650000000      1ª
1      Banco do Brasil          11%                27250000000      2ª
2             Bradesco          -2%                25050000000      3ª
3            Petrobras         -13%                17000000000      4ª
4                 Vale          38%                15000000000      5ª
5                Caixa          -7%                14300000000      6ª
6             Localiza          90%                11500000000      7ª
7               Brahma          20%                 9800000000      8ª
8               Natura          -2%                 9750000000      9ª
9                 Skol           7%                 9500000000     10ª
10               Sadia          16%                 9000000000     11ª
11                Vivo          18%                 8500000000     12ª
12  Rede D’or São Luiz          54%                 6850000000     13ª
13              Nubank          30%                 6750000000     14ª
14             Marfrig          11%                 6750000000     15ª
15      Latam Airlines          10%                 6100000000     16ª
16    Assai Atacadista         -13%                 6000000000     17ª
17              Raízen         -24%                 5450000000     18ª
18      Magazine Luiza           0%                 4970000000     19ª
19          Antarctica          -4%                 4960000000     20ª
20              Suzano          34%                 4600000000     21ª
21            Ipiranga          30%                 4590000000     22ª
22             Embraer           6%                 4320000000     23ª
23             Braskem           6%                 4135000000     24ª
24            Atacadão         -39%                 4100000000     25ª
25              Unidas          22%                 3830000000     26ª
26              Sabesp          27%                 3755000000     27ª
27              Klabin          -4%                 3465000000     28ª
28              Movida          -9%                 3410000000     29ª
29   PagSeguro Digital          27%                 3150000000     30ª
30              Renner          -4%                 3075000000     31ª
31               Camil           0%                 2870000000     32ª
32          Votorantim          10%                 2845000000     33ª
33               Globo           5%                 2790000000     34ª
34               Vibra         -16%                 2765000000     35ª
35             XP Inc.          -3%                 2720000000     36ª
36               BNDES          13%                 2715000000     37ª
37              Gerdau          26%                 2680000000     38ª
38    Seguradora Porto          16%                 2500000000     39ª
39              Itambé         -21%                 2220000000     40ª
40            SmartFit          -7%                 2160000000     41ª
41             Minerva          54%                 2130000000     42ª
42               Stone           0%                 2080000000     43ª
43            Perdigão          18%                 1950000000     44ª
44          Neoenergia          -8%                 1940000000     45ª
45             Hapvida          -2%                 1885000000     46ª
46                  B3           6%                 1790000000     47ª
47         Sul América           8%                 1785000000     48ª
48              Ypióca          14%                 1770000000     49ª
49           Banco Pan           0%                 1710000000     50ª

In [149]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 4 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Marca                      50 non-null     object
 1   Variação (%)               50 non-null     object
 2   Valor em bilhões de reais  50 non-null     int64
 3   Posicao                    50 non-null     object
dtypes: int64(1), object(3)
memory usage: 1.7+ KB

In [151]:
# Salva o DataFrame em um arquivo CSV
df.to_csv('dados/Marcas_Valores.csv', index=False)